[global]
pid = /home/xtreamcodes/iptv_xtream_codes/php/var/run/php-fpm.pid
error_log = /home/xtreamcodes/iptv_xtream_codes/php/var/log/php-fpm.log
daemonize = yes

include=/home/xtreamcodes/iptv_xtream_codes/php/etc/fpm-pool.d/*.conf
