<?php
require '../init.php';
session_start();
if (empty($_SESSION['client_loggedin']) && $_SESSION['client_loggedin'] !== true && empty($_SESSION['cl_data'])) { header('Location: index.php'); exit; }
$client=$_SESSION['cl_data']??[]; $username=(string)($client['username']??''); $password=(string)($client['password']??'');
$userInfo=ipTV_streaming::GetUserInfo(null,$username,$password,true,true,true,['movie']);
$movies=$userInfo['channels']??[]; $categories=[]; foreach($movies as $movie){$categories[$movie['category_name']??'Uncategorized'][]=$movie;}
$baseUrl=rtrim((string)(ipTV_lib::$StreamingServers[SERVER_ID]['site_url']??''),'/'); $vlc=(ipTV_lib::$settings['client_area_plugin']??'')==='vlc';
function vod_escape($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Movies</title><link rel="stylesheet" href="css/main.css"><link rel="stylesheet" href="css/greedynav.css"><link rel="stylesheet" href="css/reset.min.css"><script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script><script src="js/greedynav.js"></script></head><body>
<div class="header"><div class="logo"></div><div class="button_Live"><img src="images/live_btn.png" onclick="parent.location='live.php'"></div><div class="button_Movies"><img src="images/videos_btn_hover.png"></div><div class="button_Radio"><img src="images/radio_btn.png" onclick="parent.location='radio.php'"></div><div class="User"><img src="images/user_icon.png"><a style="margin-left:10px;color:#C60"><?=vod_escape($username)?></a><ul><li><a style="color:#c60;font-size:12px">Expire Date:</a><a style="margin-left:10px;color:#fff;font-size:12px"><?php echo !empty($client['exp_date'])?date('d/m/Y H:i',$client['exp_date']):'Unlimited';?></a></li><li><a href="index.php?action=logout"><img src="images/logout_btn.png"></a></li></ul></div></div>
<div class="wrapper"><div data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="search"><center><nav class="greedy-nav"><button><div class="hamburger"></div></button><ul class="visible-links"><li><a href="vod.php">All</a></li><?php foreach(array_keys($categories) as $category){?><li><a href="vod.php?cat_id=<?=rawurlencode($category)?>"><?=vod_escape($category)?></a></li><?php }?></ul><ul class="hidden-links hidden"></ul></nav></center>
<?php $selected=$_GET['cat_id']??null; foreach($categories as $category=>$items){if($selected!==null&&(string)$selected!==(string)$category)continue; foreach($items as $movie){$id=(int)($movie['id']??0);$name=(string)($movie['stream_display_name']??'');$icon=(string)($movie['stream_icon']??'');$extension=(string)($movie['container_extension']??'mp4');$url=$baseUrl.'/movie/'.rawurlencode($username).'/'.rawurlencode($password).'/'.$id.'.'.$extension;$action=$vlc?"post('player.php',{link:'".addslashes($url)."',display_name:'".addslashes($name)."'});":"window.location.href='".addslashes($url)."';";?>
<div class="movie_Frame"><div class="movie_thumb"><?php if($icon!==''){?><img width="214" height="317" src="<?=vod_escape($icon)?>"><?php }else{?><img width="214" height="317" src="images/no_poster.jpg"><?php }?></div><div class="movie_Info"><h3><?=vod_escape($name)?></h3><button onclick="<?=vod_escape($action)?>">Play</button></div></div>
<?php }}?></div></div><div class="footer"><img style="float:right" src="images/footer.png"></div></body></html>
